# Generated by Django 2.2.10 on 2020-05-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
            ],
            options={
                'verbose_name': 'answer',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='start on')),
                ('finish_date', models.DateTimeField(db_index=True, verbose_name='finish on')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'poll',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('qtype', models.IntegerField(choices=[(1, 'text'), (2, 'one option'), (3, 'several options')], verbose_name='type')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
            options={
                'verbose_name': 'question',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_answer', models.CharField(max_length=255, null=True, verbose_name='typed answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to='polls.Question')),
                ('selected_answers', models.ManyToManyField(blank=True, related_name='_useranswer_selected_answers_+', to='polls.Answer', verbose_name='selected answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': "user's answer",
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question'),
        ),
    ]
